name: Docker Build and Push

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Sanitize version tag
        id: sanitize-version
        run: |
          RAW_VERSION=${GITHUB_REF#refs/tags/}
          CLEAN_VERSION=$(echo "$RAW_VERSION" | sed 's/^v//; s/[^a-zA-Z0-9.-]/-/g')
          echo "SANITIZED_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./docker  # 指向包含Dockerfile的目录
          file: ./docker/Dockerfile  # 显式路径
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/weather-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/weather-app:${{ env.SANITIZED_VERSION }}
