version: '3.8'

services:
  app:
    image: your-dockerhub-username/weather-app:latest
    container_name: weather-app
    environment:
      - API_KEY=${API_KEY}  
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - weather-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  nginx:
    image: nginx:alpine
    container_name: weather-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl 
      - app
    restart: unless-stopped
    networks:
      - weather-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup  
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
